### ISSUE TITLE
Can't add other blockchain

### ISSUE THREAD

**Issue by alexanderhawl** [olekon/justsmartcontracts#17]
In the past version, I can add other blockchains, such as kava,cronos,moonbeam. But now, There are just some special chains. Is it possible to recover this function?

**Comment by mshakeg** [comment]
Yes please, would really appreciate if this feature could be added back.

**Comment by mshakeg** [comment]
The following tool allows for this, however you have to connect your metamask and set the network that you'd like to interact with.

https://neptunemutual.com/web3-tools/solidity-abi-encoder-online/

**Comment by olekon** [comment]
Hey, sorry for late response. This feature is definitely on top of my todo-list

**Comment by olekon** [comment]
I still don't have much time for implementing the requested feature, but I added lots of new chains.

**Comment by mshakeg** [comment]
@olekon dynamically loading all EVM chains based on [chainid.network/chains.json](https://chainid.network/chains.json) list might be a better solution

**Comment by olekon** [comment]
yes, thanks for the source
