### ISSUE TITLE
Address array

### ISSUE THREAD

**Issue by jrcourtault-xdev** [olekon/justsmartcontracts#19]
![image](https://github.com/olekon/justsmartcontracts/assets/89092943/a8f5172e-c59d-4efd-989c-a29f4cc153a3)
In the upper form, I tried many way to pass an address array :
- ['0xEf2c58eA671ff73Ba0dc465828C879698ff0EEf4']
- ["0xEf2c58eA671ff73Ba0dc465828C879698ff0EEf4"]
- [0xEf2c58eA671ff73Ba0dc465828C879698ff0EEf4]
- "0xEf2c58eA671ff73Ba0dc465828C879698ff0EEf4"
- ...

But, I get always this error :
![image](https://github.com/olekon/justsmartcontracts/assets/89092943/ab73541d-922f-4dad-b15c-60c39f14153a)

Is there a bug, or what is the correct syntax ?

PS : I really like JustSmartContracts, thank you for this tool !

**Comment by olekon** [comment]
Hi, now it should be fixed, check please

**Comment by jrcourtault-xdev** [comment]
Thank you Olekon !!!
